create table if not exists public.lotto_draws (
  id bigint generated by default as identity primary key,
  numbers integer[] not null,
  bonus integer not null,
  created_at timestamptz not null default now(),
  constraint lotto_draws_numbers_length check (array_length(numbers, 1) = 6),
  constraint lotto_draws_bonus_range check (bonus between 1 and 45),
  constraint lotto_draws_bonus_not_in_numbers check (bonus <> all(numbers))
);

create index if not exists lotto_draws_created_at_idx
  on public.lotto_draws (created_at desc);

grant select, insert on public.lotto_draws to service_role;
